Improve readme
saleor/saleor-checkout pull request #120
Opened 2022-06-21 13:51 UTC by 2can

2022-06-21 13:54 UTC, dekoza approved these changes

2022-06-21 14:53 UTC, timuric requested changes

2022-06-21 14:53 UTC, timuric commented on README.md
> +4. Setup `Payment methods` in your Mollie dashboard, select: Settings -> Website Profiles -> Payment methods
Let's say "Enable" instead of "Setup"?

2022-06-22 13:45 UTC, 2can commented on README.md
> +4. Setup `Payment methods` in your Mollie dashboard, select: Settings -> Website Profiles -> Payment methods
@timuric done

2022-06-22 14:35 UTC, timuric approved these changes

2022-06-22 14:36 UTC, merged