Fix loading states in checkout
saleor/saleor-checkout pull request #151
Opened 2022-07-19 08:11 UTC by bmigirl

- Remove redundant loading conditions
- Wrap whole checkout into suspense and add checkout skeleton

2022-07-19 08:13 UTC, Cloud11PL approved these changes

2022-07-19 08:36 UTC, orzechdev approved these changes

2022-07-19 08:53 UTC, mmiszy requested changes

2022-07-19 08:53 UTC, mmiszy commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
Why the downgrade?

2022-07-19 09:20 UTC, bmigirl commented on apps/checkout/src/CheckoutSkeleton.tsx
> +            />
Yeah, this was done according to [the designs](https://www.figma.com/file/oBQhZFwyFcXauxFrb3mbRb/Saleor-checkout?node-id=148%3A4102) but I think leaving it with `Pay` label and disabled makes more sense

2022-07-19 10:25 UTC, mmiszy approved these changes

2022-07-20 00:17 UTC, mmiszy commented
After merging #146 this PR has conflicts but hopefully it'll be easy to reapply these changes to `packages/checkout-storefront` @bmigirl 
Let me know if you have any questions!

2022-07-21 11:09 UTC, merged