Update bug report with comment about using envinfo
saleor/saleor-checkout pull request #172
Opened 2022-07-26 08:32 UTC by witoszekdev

I want to merge this because it adds a comment to bug report template about using `envinfo` package to gather environment data automatically

2022-07-26 08:33 UTC, bmigirl approved these changes

2022-07-26 10:48 UTC, mmiszy approved these changes

2022-07-26 12:24 UTC, mmiszy requested changes

2022-07-26 12:24 UTC, mmiszy commented on apps/saleor-app-checkout/constants.ts
>    apiUrl: "NEXT_PUBLIC_SALEOR_API_URL",
This is unrelated

2022-07-26 12:24 UTC, mmiszy commented on packages/env-vars/index.js
This is unrelated

2022-07-27 08:15 UTC, mmiszy approved these changes

2022-07-27 08:17 UTC, merged